version: '3'
services:
  manager:
    env_file:
      - .env
    container_name: manager
    build: ./client-manager
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    env_file:
      - .env
    container_name: db
    build: ./client-manager/db
    ports:
      - "5432:5432"
    volumes:
      - ./client-manager/data/db:/var/lib/postgresql/data
