version: '3'
services:
  manager:
    env_file:
      - .env
    container_name: manager
    build: ./client-manager
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  db:
    env_file:
      - .env
    container_name: db
    build: ./client-manager/db
    ports:
      - "5432:5432"
    volumes:
      - ./client-manager/data/db:/var/lib/postgresql/data
