version: '3'
services:
  manager:
    container_name: manager
    build: ./client-manager
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
